### PR TITLE
move common.tmp_dir default value definition to viper

### LINKED ISSUE #48: Env var values not being loaded without a config file definition
@wwoytenko I encountered a problem where environment variables are not being loaded if their config isn't defined in a config file. It seems that this is a known Viper issue: https://github.com/spf13/viper/issues/584

I'll come up with a PR to solve this issue, changing the `common.tmp_dir` default definition.

We can also utilize this PR to set a default behavior for `storage` config. I see these possible scenarios
- Define default storage to directory storage on `~/dumps` -- this would allow Docker users to map a volume to `/home/greenmask/dumps` and use it without needing to specify the `storage.directory.path` configuration
- Require storage configuration and error out in case none is provided

### PR DESCRIPTION
**Pull request by joao-zanutto**
closes #48 

@wwoytenko please feel free to list other default values that should be added

### CODE REVIEW

**Review by wwoytenko — CHANGES_REQUESTED** [review]
Add the 
Could you add the pg_bin_path as well?

Add into `root.init()` the next bunch of code

``` go
	if err := viper.BindEnv("common.pg_bin_path", "COMMON_PG_BIN_PATH"); err != nil {
		log.Fatal().Err(err).Msg("")
	}
```

**Comment by wwoytenko** [comment]
There was something broken in #51 and it will be fixed in #52. I will let you know one that is merged into the main

**Comment by wwoytenko** [comment]
#52 is merged

**Comment by joao-zanutto** [comment]
Closing this PR as we chose to go another route

**Pull request closed without merging**
