### PR TITLE
fix unmarshal dump.transformation from env variable

### LINKED ISSUE #60: Feature: add JSON parsing to dump.transformation attribute
Currently, the only way to pass a configuration to the `dump.tansformation` is through YAML, making it imperative to use a config file to configure a transformation.
Adding a JSON parser to this attribute will allow users to configure Greenmask entirely from environment variables, not needing to mount any volume or file. 

This is specially useful when running Greenmask from a container, because many cloud providers offer container platforms that have environment variable and secret management easily integrated for no additional cost, however, preparing and mounting a volume will require some additional configuration and planning, alongside with other infrastructure considerations.

### PR DESCRIPTION
**Pull request by joao-zanutto**
- Enable dump transformation configuration through environment variable `DUMP_TRANSFORMATION` using JSON

closes #60

### CODE REVIEW

**Comment by joao-zanutto** [comment]
@wwoytenko I spent some time debugging and after a while I realized that this PR actually solves the problem entirely, as described in my update in the latest comment in#60

**Comment by wwoytenko** [comment]
I will check it carefully on this week. I have to check the custom transformers protocol that is not described in the docs but implemented. I will let you know once it is validated

**Comment by wwoytenko** [comment]
I believe I will be able to check it only in the next week.

**Comment by wwoytenko** [comment]
According to the limitation of `mapstructure` and viper we can't publish this because it raises #76 

The related issue is [there](https://github.com/spf13/viper/issues/373)

I've just implemented workaround #80 and it is not backward compatible with this PR

**Pull request closed without merging**
